# Generated by Django 6.0.5 on 2026-05-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='webhook_password',
            field=models.CharField(blank=True, help_text='Password untuk Basic Auth callback', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='webhook_username',
            field=models.CharField(blank=True, help_text='Username untuk Basic Auth callback', max_length=150, null=True),
        ),
    ]
