# Generated by Django 6.0.5 on 2026-05-28 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_apikey_webhook_password_apikey_webhook_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama deskriptif perangkat', max_length=100)),
                ('ae_title', models.CharField(blank=True, default='', help_text='DICOM AE Title', max_length=64)),
                ('host', models.GenericIPAddressField(help_text='IP Address perangkat')),
                ('port', models.PositiveIntegerField(default=104, help_text='Port DICOM')),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unverified', 'Belum Diverifikasi')], default='unverified', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['host', 'port'],
            },
        ),
    ]
