# Generated by Django 6.0.5 on 2026-05-29 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_dicomdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama aturan perutean', max_length=150)),
                ('modality', models.CharField(blank=True, default='', help_text='Filter Modality (cth: CT, MR, DX) atau kosongkan untuk semua', max_length=50)),
                ('patient_id_prefix', models.CharField(blank=True, default='', help_text='Prefiks Patient ID atau kosongkan untuk semua', max_length=50)),
                ('study_desc_contains', models.CharField(blank=True, default='', help_text='Filter deskripsi studi mengandung teks', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Aturan aktif atau tidak')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_device', models.ForeignKey(help_text='Node DICOM tujuan perutean', on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='bridge.dicomdevice')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=255)),
                ('modality', models.CharField(max_length=50)),
                ('target_device_name', models.CharField(max_length=150)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.routingrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('frequency', models.CharField(choices=[('hourly', 'Setiap Jam'), ('daily', 'Setiap Hari (Tengah Malam)'), ('weekly', 'Setiap Minggu (Hari Minggu)')], default='daily', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_schedules', to='bridge.dicomdevice')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_studies', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.syncschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
