# Generated by Django 6.0.5 on 2026-05-29 22:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0004_routingrule_routinglog_syncschedule_synclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(blank=True, default='', max_length=100)),
                ('accession_number', models.CharField(blank=True, default='', max_length=50)),
                ('modality', models.CharField(blank=True, default='', max_length=50)),
                ('target_device_name', models.CharField(max_length=150)),
                ('status', models.CharField(default='Success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.dicomdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
