# Generated by Django 6.0.5 on 2026-08-04 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_transferlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accession_number', models.CharField(max_length=50, unique=True)),
                ('patient_id', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=255)),
                ('birth_date', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('procedure_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('study_instance_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='Berhasil', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
