# Generated by Django 6.0.5 on 2026-08-19

from django.db import migrations, models


def add_syncschedule_fields_if_missing(apps, schema_editor):
    """Menambahkan kolom run_hour, run_minute, dan modality_filter jika belum ada di database"""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM bridge_syncschedule")
        existing_columns = [row[0] for row in cursor.fetchall()]

        if 'run_hour' not in existing_columns:
            cursor.execute("ALTER TABLE bridge_syncschedule ADD COLUMN run_hour SMALLINT UNSIGNED NOT NULL DEFAULT 0")
        if 'run_minute' not in existing_columns:
            cursor.execute("ALTER TABLE bridge_syncschedule ADD COLUMN run_minute SMALLINT UNSIGNED NOT NULL DEFAULT 0")
        if 'modality_filter' not in existing_columns:
            cursor.execute("ALTER TABLE bridge_syncschedule ADD COLUMN modality_filter VARCHAR(100) NOT NULL DEFAULT ''")


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0006_docdocument'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_syncschedule_fields_if_missing, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='syncschedule',
                    name='modality_filter',
                    field=models.CharField(blank=True, default='', help_text='Filter modalitas cth: CT,MR — kosongkan untuk semua', max_length=100),
                ),
                migrations.AddField(
                    model_name='syncschedule',
                    name='run_hour',
                    field=models.PositiveSmallIntegerField(default=0, help_text='Jam pengiriman (0-23) untuk jadwal harian/mingguan'),
                ),
                migrations.AddField(
                    model_name='syncschedule',
                    name='run_minute',
                    field=models.PositiveSmallIntegerField(default=0, help_text='Menit pengiriman (0-59)'),
                ),
                migrations.AlterField(
                    model_name='syncschedule',
                    name='frequency',
                    field=models.CharField(choices=[('hourly', 'Setiap Jam'), ('daily', 'Setiap Hari'), ('weekly', 'Setiap Minggu (Hari Minggu)')], default='daily', max_length=20),
                ),
            ]
        ),
    ]
